(() => {
  const pending=JSON.parse(localStorage.getItem("encore-intermission-session")||"null"),sessionShow=JSON.parse(sessionStorage.getItem("encore-current-show")||"{}"),show=Object.keys(sessionShow).length?sessionShow:(pending?.show||{}),language=localStorage.getItem("encore-language")||"zh",zh=language==="zh",ticketLanguage=show.ticketLanguage||language,title=(zh?show.titleZh:show.titleEn)||"ENCORE",total=Math.round((show.duration||90)*60),hasBreak=Boolean(show.intermission),absenceLimit=300000,showKey=`${show.titleZh||show.titleEn||"Encore"}-${show.duration||0}`,resumesIntermission=Boolean(pending&&pending.showKey===showKey&&pending.phase==="intermission"),resumeActTwo=localStorage.getItem("encore-resume-act-two")===showKey;
  let act=resumesIntermission?pending.act:1,focusRemaining=resumesIntermission?pending.focusRemaining:(hasBreak?Math.floor(total/2):total),breakRemaining=resumesIntermission?pending.breakRemaining:0,elapsed=resumesIntermission?pending.elapsed:0,paused=false,awayAt=null,awayTimeout=null,saved=false,failed=false;
  const stage=document.querySelector("#stage"),timer=document.querySelector("#timer"),curtainTimer=document.querySelector("#curtain-timer"),pause=document.querySelector("#pause-button"),leave=document.querySelector("#leave-button"),actLabel=document.querySelector("#act-label"),detail=document.querySelector("#focus-detail"),curtainKicker=document.querySelector("#curtain-kicker"),curtainTitle=document.querySelector("#curtain-title"),curtainDetail=document.querySelector("#curtain-detail"),curtainAction=document.querySelector("#curtain-action"),intermissionActions=document.querySelector("#intermission-actions"),storeIntermission=document.querySelector("#store-intermission"),leaveIntermission=document.querySelector("#leave-intermission");
  const time=value=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`,dateText=(date=new Date())=>`${date.getFullYear()}/${date.getMonth()+1}/${date.getDate()}`,watchedMinutes=()=>Math.max(1,Math.round(elapsed/60)),go=hash=>location.href=`home.html${hash}`;
  function setStageText(){actLabel.textContent=hasBreak?`· ACT ${act===1?"I":"II"}`:"";actLabel.hidden=!hasBreak;document.querySelector("#show-name").textContent=title;detail.textContent=zh?"演出已经开始，请将注意力留在此刻":"The performance has begun. Keep your attention here.";document.querySelector("#absence-rule").innerHTML=zh?"离开剧场时将暂停计时；超过 5 分钟未返回，本场将作废。<br>演出开始 15 分钟后可提前离场；票根将如实记录本次已投入的专注时间。":"Leaving pauses the timer. If you are away for over 5 minutes, this session will be void.<br>After 15 minutes, you may leave early; your ticket will reflect only the time you spent focusing.";pause.textContent=paused?(zh?"继续":"Resume"):(zh?"暂停":"Pause");timer.textContent=time(focusRemaining)}
  function updateLeave(){const remaining=Math.max(0,900-elapsed);leave.disabled=remaining>0;leave.textContent=remaining>0?(zh?`离开剧场 · ${time(remaining)}`:`Leave theatre · ${time(remaining)}`):(zh?"离开剧场":"Leave theatre")}
  function openStage(){stage.classList.remove("is-curtain");pause.hidden=false;leave.hidden=false;setStageText();updateLeave()}
  function clearIntermission(){localStorage.removeItem("encore-intermission-session");localStorage.removeItem("encore-resume-act-two")}
  function persistIntermission(){const previous=JSON.parse(localStorage.getItem("encore-intermission-session")||"null");localStorage.setItem("encore-intermission-session",JSON.stringify({id:previous?.id||`intermission-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,phase:"intermission",show,showKey,act,focusRemaining,breakRemaining,elapsed,savedAt:Date.now()}))}
  function openIntermission(){breakRemaining=show.intermission*60;stage.classList.add("is-curtain");pause.hidden=true;leave.hidden=true;curtainKicker.textContent="INTERMISSION";curtainTitle.textContent=zh?"中场休息":"Intermission";curtainDetail.textContent=zh?"休息结束后，将自动开始下半场。":"Act II will begin automatically when the interval ends.";curtainTimer.hidden=false;curtainTimer.textContent=time(breakRemaining);curtainAction.hidden=false;curtainAction.textContent=zh?"提前回到座位":"Start Act II";intermissionActions.hidden=false;storeIntermission.hidden=false;storeIntermission.textContent=zh?"暂存本场，稍后继续":"Save this session for later";leaveIntermission.textContent=zh?"直接离开":"Leave now"}
  function startActTwo(){clearIntermission();act=2;focusRemaining=total-Math.floor(total/2);openStage()}
  function saveTicket({status="completed",actualMinutes=watchedMinutes()}={}){if(saved)return;const intermissionId=status==="intermission"?pending?.id:null,existing=JSON.parse(localStorage.getItem("encore-tickets")||"[]");if(intermissionId&&existing.some(ticket=>ticket.intermissionId===intermissionId)){clearIntermission();saved=true;return}clearIntermission();saved=true;const date=new Date();existing.push({id:`ticket-${date.getTime()}-${Math.random().toString(36).slice(2,7)}`,title,venue:zh?show.venueZh:show.venueEn,duration:show.duration||90,actualMinutes,completedAt:date.toISOString(),completedDate:show.ticketDate||dateText(date),intermission:show.intermission,floor:show.floor,row:show.row,seat:show.seat,language:ticketLanguage,status,intermissionId});localStorage.setItem("encore-tickets",JSON.stringify(existing))}
  function showCurtain({kicker,heading,copy,action}){intermissionActions.hidden=true;const finalCurtain=kicker==="CURTAIN CALL";stage.classList.remove("is-entering");stage.classList.add("is-closing");pause.hidden=true;leave.hidden=true;curtainKicker.textContent=kicker;curtainTitle.textContent=heading;curtainTimer.hidden=finalCurtain;curtainTimer.textContent="";curtainDetail.textContent=copy;curtainAction.hidden=false;curtainAction.textContent=action;if(finalCurtain)document.querySelector("#absence-rule").textContent=zh?"谢谢你，把这一段时间留给自己。":"Thank you for giving this time to yourself.";curtainAction.onclick=()=>go("#wallet");setTimeout(()=>{stage.classList.remove("is-closing");stage.classList.add("is-curtain")},matchMedia("(prefers-reduced-motion: reduce)").matches?0:460)}
  function curtainCall(early=false){saveTicket();showCurtain({kicker:early?"EARLY CURTAIN":"CURTAIN CALL",heading:early?(zh?"你提前离开了剧场。":"You left the theatre early."):(zh?"今晚的演出结束了。":"Tonight's performance has ended."),copy:early?(zh?`实际观演 ${watchedMinutes()} 分钟，票根已为你保留。`:`${watchedMinutes()} minutes watched. Your ticket is saved.`):"",action:zh?"将票根收入票夹":"Collect your ticket"})}
  function failForAbsence(){if(failed||saved)return;failed=true;paused=true;saveTicket({status:"failed",actualMinutes:0});showCurtain({kicker:"MISSED PERFORMANCE",heading:zh?"本场未能观演。":"This performance was missed.",copy:zh?"离开剧场超过 5 分钟，本次专注未完成。":"You were away for over 5 minutes, so this focus session was not completed.",action:zh?"查看票夹":"View tickets"})}
  function markAway(){if(saved||failed||paused||stage.classList.contains("is-curtain")||awayAt)return;awayAt=Date.now();awayTimeout=setTimeout(failForAbsence,absenceLimit)}
  function returnFromAway(){if(!awayAt||saved||failed)return;const absence=Date.now()-awayAt;awayAt=null;clearTimeout(awayTimeout);awayTimeout=null;if(absence>absenceLimit)failForAbsence()}
  pause.addEventListener("click",()=>{paused=!paused;pause.textContent=paused?(zh?"继续":"Resume"):(zh?"暂停":"Pause")});leave.addEventListener("click",()=>{if(!leave.disabled)curtainCall(true)});curtainAction.addEventListener("click",()=>{if(breakRemaining>0)startActTwo()});storeIntermission.addEventListener("click",()=>{persistIntermission();go("#explore")});leaveIntermission.addEventListener("click",()=>{saveTicket({status:"intermission",actualMinutes:watchedMinutes()});go("#wallet")});document.addEventListener("visibilitychange",()=>{if(document.hidden)markAway();else returnFromAway()});window.addEventListener("blur",markAway);window.addEventListener("focus",returnFromAway);
  setStageText();updateLeave();if(resumesIntermission){const passed=Math.floor((Date.now()-pending.savedAt)/1000);if(resumeActTwo)startActTwo();else if(passed>=breakRemaining){saveTicket({status:"intermission",actualMinutes:watchedMinutes()});showCurtain({kicker:"INTERMISSION EXIT",heading:zh?"中场休息结束了。":"The intermission has ended.",copy:zh?`你已专注上半场 ${watchedMinutes()} 分钟，票根已为你保留。`:`You focused for ${watchedMinutes()} minutes in Act I. Your ticket is saved.`,action:zh?"查看票夹":"View tickets"})}else{breakRemaining-=passed;stage.classList.add("is-curtain");pause.hidden=true;leave.hidden=true;curtainKicker.textContent="INTERMISSION";curtainTitle.textContent=zh?"中场休息":"Intermission";curtainDetail.textContent=zh?"休息结束后，将自动开始下半场。":"Act II will begin automatically when the interval ends.";curtainTimer.hidden=false;curtainTimer.textContent=time(breakRemaining);curtainAction.hidden=false;curtainAction.textContent=zh?"提前回到座位":"Start Act II";intermissionActions.hidden=false;storeIntermission.hidden=true;leaveIntermission.textContent=zh?"直接离开":"Leave now"}}
  setTimeout(()=>stage.classList.remove("is-entering"),matchMedia("(prefers-reduced-motion: reduce)").matches?0:180);setInterval(()=>{if(paused||awayAt||failed)return;if(stage.classList.contains("is-curtain")){if(breakRemaining>0){breakRemaining--;curtainTimer.textContent=time(breakRemaining);if(breakRemaining===0)startActTwo()}return}if(focusRemaining>0){focusRemaining--;elapsed++}timer.textContent=time(focusRemaining);updateLeave();if(focusRemaining===0){if(hasBreak&&act===1)openIntermission();else curtainCall(false)}},1000);
})();
