const show=JSON.parse(sessionStorage.getItem("encore-current-show")||"{}"),language=localStorage.getItem("encore-language")||"zh",zh=language==="zh",title=(zh?show.titleZh:show.titleEn)||"ENCORE",total=Math.round((show.duration||90)*60),hasBreak=Boolean(show.intermission),absenceLimit=300000;
let act=1,focusRemaining=hasBreak?Math.floor(total/2):total,breakRemaining=0,elapsed=0,paused=false,awayAt=null,awayTimeout=null,saved=false,failed=false;
const stage=document.querySelector("#stage"),timer=document.querySelector("#timer"),curtainTimer=document.querySelector("#curtain-timer"),pause=document.querySelector("#pause-button"),leave=document.querySelector("#leave-button"),actLabel=document.querySelector("#act-label"),detail=document.querySelector("#focus-detail"),curtainKicker=document.querySelector("#curtain-kicker"),curtainTitle=document.querySelector("#curtain-title"),curtainDetail=document.querySelector("#curtain-detail"),curtainAction=document.querySelector("#curtain-action");
const time=value=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`,dateText=(date=new Date())=>`${date.getFullYear()}/${date.getMonth()+1}/${date.getDate()}`,watchedMinutes=()=>Math.max(1,Math.round(elapsed/60));
function setStageText(){actLabel.textContent=hasBreak?`· ACT ${act===1?"I":"II"}`:"";actLabel.hidden=!hasBreak;document.querySelector("#show-name").textContent=title;document.querySelector("#focus-title").textContent=zh?`正在上演 · ${title}`:`NOW PLAYING · ${title}`;detail.textContent=zh?"演出已经开始，请将注意力留在此刻":"The performance has begun. Keep your attention here.";document.querySelector("#absence-rule").textContent=zh?"离开剧场时将暂停计时；超过 5 分钟未返回，本场将作废。":"Leaving pauses the timer. If you are away for over 5 minutes, this session will be void.";timer.textContent=time(focusRemaining)}
function updateLeave(){const remaining=Math.max(0,900-elapsed);leave.disabled=remaining>0;leave.textContent=remaining>0?(zh?`离开剧场 · ${time(remaining)}`:`Leave theatre · ${time(remaining)}`):(zh?"离开剧场":"Leave theatre")}
function openStage(){stage.classList.remove("is-curtain");pause.hidden=false;leave.hidden=false;setStageText();updateLeave()}
function openIntermission(){breakRemaining=show.intermission*60;stage.classList.add("is-curtain");pause.hidden=true;leave.hidden=true;curtainKicker.textContent="INTERMISSION";curtainTitle.textContent=zh?"中场休息":"Intermission";curtainDetail.textContent=zh?"休息结束后，将自动开始下半场。":"Act II will begin automatically when the interval ends.";curtainAction.hidden=false;curtainAction.textContent=zh?"提前回到座位":"Start Act II";curtainTimer.textContent=time(breakRemaining)}
function startActTwo(){act=2;focusRemaining=total-Math.floor(total/2);openStage()}
function saveTicket({status="completed",actualMinutes=watchedMinutes()}={}){if(saved)return;saved=true;const date=new Date(),tickets=JSON.parse(localStorage.getItem("encore-tickets")||"[]");tickets.push({id:`ticket-${date.getTime()}-${Math.random().toString(36).slice(2,7)}`,title,venue:zh?show.venueZh:show.venueEn,duration:show.duration||90,actualMinutes,completedAt:date.toISOString(),completedDate:dateText(date),status});localStorage.setItem("encore-tickets",JSON.stringify(tickets))}
function showCurtain({kicker,heading,copy,action}){stage.classList.add("is-curtain");pause.hidden=true;leave.hidden=true;curtainKicker.textContent=kicker;curtainTitle.textContent=heading;curtainTimer.textContent="✦";curtainDetail.textContent=copy;curtainAction.hidden=false;curtainAction.textContent=action;curtainAction.onclick=()=>location.href="home.html#wallet"}
function curtainCall(early=false){saveTicket();showCurtain({kicker:early?"EARLY CURTAIN":"CURTAIN CALL",heading:early?(zh?"你提前离开了剧场。":"You left the theatre early."):(zh?"今晚的演出结束了。":"Tonight's performance has ended."),copy:early?(zh?`实际观演 ${watchedMinutes()} 分钟，票根已为你保留。`:`${watchedMinutes()} minutes watched. Your ticket is saved.`):(zh?"谢谢你，把这一段时间留给自己。":"Thank you for giving this time to yourself."),action:zh?"将票根收入票夹":"Collect your ticket"})}
function failForAbsence(){if(failed||saved)return;failed=true;paused=true;saveTicket({status:"failed",actualMinutes:0});showCurtain({kicker:"MISSED PERFORMANCE",heading:zh?"本场未能观演。":"This performance was missed.",copy:zh?"离开剧场超过 5 分钟，本次专注未完成。":"You were away for over 5 minutes, so this focus session was not completed.",action:zh?"查看票夹":"View tickets"})}
function markAway(){if(saved||failed||paused||stage.classList.contains("is-curtain")||awayAt)return;awayAt=Date.now();awayTimeout=setTimeout(failForAbsence,absenceLimit)}
function returnFromAway(){if(!awayAt||saved||failed)return;const absence=Date.now()-awayAt;awayAt=null;clearTimeout(awayTimeout);awayTimeout=null;if(absence>absenceLimit)failForAbsence()}
pause.addEventListener("click",()=>{paused=!paused;pause.textContent=paused?(zh?"继续":"Resume"):(zh?"暂停":"Pause")});leave.addEventListener("click",()=>{if(!leave.disabled)curtainCall(true)});curtainAction.addEventListener("click",()=>{if(breakRemaining>0)startActTwo()});document.addEventListener("visibilitychange",()=>{if(document.hidden)markAway();else returnFromAway()});window.addEventListener("blur",markAway);window.addEventListener("focus",returnFromAway);
setStageText();updateLeave();setInterval(()=>{if(paused||awayAt||failed)return;if(stage.classList.contains("is-curtain")){if(breakRemaining>0){breakRemaining--;curtainTimer.textContent=time(breakRemaining);if(breakRemaining===0)startActTwo()}return}if(focusRemaining>0){focusRemaining--;elapsed++}timer.textContent=time(focusRemaining);updateLeave();if(focusRemaining===0){if(hasBreak&&act===1)openIntermission();else curtainCall(false)}},1000);
