const language = localStorage.getItem("encore-language") || "zh";
const copy = {
  zh: {
    exploreEyebrow: "今晚为你推荐", exploreTitle: "今晚，想看哪一场？", exploreIntro: "从一场演出开始，给时间一个值得期待的结尾。",
    customEyebrow: "你的专属场次", customTitle: "为自己安排一场演出。", customIntro: "从剧名到座位，为自己安排好这一晚。", presetIntro: "演出信息已带入，你也可以按需要调整。",
    walletEyebrow: "你收藏的 Encore", walletTitle: "我的票夹", walletIntro: "每张票根，都是一段已经好好度过的时间。", monthTotal: "本月观演", zeroMinutes: "0 分钟", collected: "已收藏", zeroTickets: "0 张票根", emptyNote: "第一场演出结束后，票根会在这里慢慢铺开。",
    navExplore: "探索剧目", navCustom: "自定义剧目", navWallet: "我的票夹", title: "剧目名称", titlePlaceholder: "填写剧目名称", venue: "观看地点", venuePlaceholder: "填写剧场或地点", duration: "专注时长", intermission: "中场休息", noIntermission: "无中场休息", seat: "座位号", viewing: "第几次观看", enter: "进入剧场落座", floor: "层", row: "排", seatUnit: "座", times: "第 {n} 次", posterDefault: "一段属于你的安静时光", original: "ENCORE 原创场次", minutes: "分钟", interval: "中场 {n} 分钟", noInterval: "无中场", ticketLabels: ["第一幕", "中场", "谢幕"], ticketPreview: "你的票根"
  },
  en: {
    exploreEyebrow: "CURATED FOR TONIGHT", exploreTitle: "What will you see tonight?", exploreIntro: "Start with a performance. Give time an ending to look forward to.",
    customEyebrow: "YOUR PERSONAL MATINÉE", customTitle: "Plan a performance for yourself.", customIntro: "Set the title, the seat, and everything in between.", presetIntro: "Your performance details are ready to adjust.",
    walletEyebrow: "YOUR COLLECTED ENCORES", walletTitle: "My ticket wallet", walletIntro: "Every ticket marks time you spent well.", monthTotal: "This month", zeroMinutes: "0 min", collected: "Collected", zeroTickets: "0 tickets", emptyNote: "After your first performance, your tickets will slowly gather here.",
    navExplore: "Discover shows", navCustom: "Custom show", navWallet: "My tickets", title: "Show title", titlePlaceholder: "Enter a show title", venue: "Venue", venuePlaceholder: "Enter a theatre or place", duration: "Focus duration", intermission: "Intermission", noIntermission: "No intermission", seat: "Seat", viewing: "Viewing count", enter: "Take your seat", floor: "F", row: "R", seatUnit: "S", times: "Viewing {n}", posterDefault: "A quiet time for you", original: "AN ENCORE ORIGINAL", minutes: "min", interval: "Interval {n} min", noInterval: "No interval", ticketLabels: ["Act I", "Interval", "Curtain call"], ticketPreview: "YOUR TICKET"
  }
};
const t = copy[language];
const shows = [
  { id:"witch", titleZh:"女巫", titleEn:"The Witch to Be", venueZh:"上海话剧艺术中心 D6 空间", venueEn:"D6 Space, Shanghai Dramatic Arts Centre", duration:130, intermission:10, floor:"1", row:"11", seat:"16" },
  { id:"phantom", titleZh:"歌剧魅影", titleEn:"The Phantom of the Opera", venueZh:"北京天桥艺术中心大剧场", venueEn:"Grand Theatre, Beijing Tianqiao Performing Arts Center", duration:155, intermission:20, floor:"1", row:"17", seat:"13" },
  { id:"human", titleZh:"人间失格", titleEn:"No Longer Human", venueZh:"北京保利剧院", venueEn:"Poly Theatre, Beijing", duration:210, intermission:20, floor:"1", row:"6", seat:"35" },
  { id:"interview", titleZh:"面试", titleEn:"Interview", venueZh:"北京世纪剧院", venueEn:"Century Theatre, Beijing", duration:110, intermission:0, floor:"1", row:"17", seat:"12" },
  { id:"hedwig", titleZh:"海德薇", titleEn:"Hedwig", venueZh:"上海北外滩友邦大剧院", venueEn:"AIA Grand Theatre, Shanghai", duration:100, intermission:0, floor:"1", row:"18", seat:"51" },
  { id:"sword", titleZh:"锦衣卫之刀与花", titleEn:"The Emperor's Shadow: Blades and Flowers", venueZh:"北京天桥艺术中心大剧场", venueEn:"Grand Theatre, Beijing Tianqiao Performing Arts Center", duration:180, intermission:15, floor:"1", row:"19", seat:"31" },
  { id:"six", titleZh:"六个说谎的大学生", titleEn:"Six Lying College Students", venueZh:"天津大剧院歌剧厅", venueEn:"Tianjin Grand Theatre Opera Hall", duration:135, intermission:15, floor:"3", row:"5", seat:"25" }
];
const customShow = { id:"custom", titleZh:"", titleEn:"", venueZh:"", venueEn:"", duration:90, intermission:0, floor:"", row:"", seat:"" };
let selectedShow = { ...customShow };
const showList = document.querySelector("#show-list");
const screens = document.querySelectorAll(".screen");
const tabs = document.querySelectorAll(".tab");
const titleOf = (show) => language === "zh" ? show.titleZh : show.titleEn;
const venueOf = (show) => language === "zh" ? show.venueZh : show.venueEn;
const formatInterval = (value) => value ? t.interval.replace("{n}", value) : t.noInterval;
function viewingCount(title) { const tickets = JSON.parse(localStorage.getItem("encore-tickets") || "[]"); return tickets.filter((ticket) => ticket.title?.trim() === title.trim()).length + 1; }
function applyCopy() { document.documentElement.lang = language === "zh" ? "zh-CN" : "en"; document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = t[node.dataset.i18n]; }); document.querySelector(".continue-button").childNodes[0].nodeValue = `${t.enter} `; }
function showScreen(name) { screens.forEach((screen) => screen.classList.toggle("screen--active", screen.id === `screen-${name}`)); tabs.forEach((tab) => tab.classList.toggle("tab--active", tab.dataset.screen === name)); window.scrollTo({ top:0, behavior:"smooth" }); }
function durationOptions(selected) { return Array.from({length:31},(_,i)=>90+i*5).map((value)=>`<option value="${value}" ${value===selected?"selected":""}>${value} ${t.minutes}</option>`).join(""); }
function renderShows() { showList.innerHTML = shows.map((show,index)=>`<button class="show-option" type="button" data-index="${index}"><span class="show-option__art poster-art--${show.id}" aria-hidden="true"><i></i><i></i><i></i></span><span class="show-option__copy"><small>${venueOf(show)}</small><b>${titleOf(show)}</b><em>${show.duration} ${t.minutes} · ${formatInterval(show.intermission)}</em></span><span class="show-option__arrow">›</span></button>`).join(""); }
function updatePoster() { const title = titleOf(selectedShow).trim() || t.posterDefault; document.querySelector("#poster-card").className=`poster-card poster-card--${selectedShow.id}`; document.querySelector("#poster-kicker").textContent=venueOf(selectedShow).trim()||t.original; document.querySelector("#poster-title").textContent=title; document.querySelector("#poster-meta").textContent=`${selectedShow.duration} ${t.minutes.toUpperCase()} · ${formatInterval(selectedShow.intermission).toUpperCase()}`; }
function renderCustom(show) { selectedShow={...show}; const preset=show.id!=="custom"; document.querySelector("#custom-title").textContent=preset ? (language==="zh"?`今晚观看《${titleOf(show)}》`:`Tonight: ${titleOf(show)}`) : t.customTitle; document.querySelector("#custom-subtitle").textContent=preset?t.presetIntro:t.customIntro; document.querySelector("#settings-list").innerHTML=`<label class="form-row form-row--title"><span class="form-label">${t.title}</span><input id="show-title" value="${show.id==="custom"?"":titleOf(show)}" placeholder="${t.titlePlaceholder}" maxlength="42" /></label><label class="form-row"><span class="form-label">${t.venue}</span><input id="show-venue" value="${venueOf(show)}" placeholder="${t.venuePlaceholder}" maxlength="55" /></label><label class="form-row"><span class="form-label">${t.duration}</span><select id="show-duration">${durationOptions(show.duration)}</select></label><label class="form-row"><span class="form-label">${t.intermission}</span><select id="show-intermission"><option value="0" ${show.intermission===0?"selected":""}>${t.noIntermission}</option><option value="10" ${show.intermission===10?"selected":""}>10 ${t.minutes}</option><option value="15" ${show.intermission===15?"selected":""}>15 ${t.minutes}</option><option value="20" ${show.intermission===20?"selected":""}>20 ${t.minutes}</option></select></label><div class="form-row form-row--seat"><span class="form-label">${t.seat}</span><span class="seat-inputs"><input id="show-floor" inputmode="numeric" value="${show.floor}" placeholder="${t.floor}" /><i>${t.floor}</i><input id="show-row" inputmode="numeric" value="${show.row}" placeholder="${t.row}" /><i>${t.row}</i><input id="show-seat" inputmode="numeric" value="${show.seat}" placeholder="${t.seatUnit}" /><i>${t.seatUnit}</i></span></div><div class="form-row"><span class="form-label">${t.viewing}</span><strong id="viewing-count">${t.times.replace("{n}",viewingCount(titleOf(show)||"untitled"))}</strong></div>`; document.querySelectorAll("#settings-list input,#settings-list select").forEach((input)=>input.addEventListener("input",syncForm)); updatePoster(); }
function syncForm() { const title=document.querySelector("#show-title").value; const venue=document.querySelector("#show-venue").value; selectedShow={...selectedShow,titleZh:title,titleEn:title,venueZh:venue,venueEn:venue,duration:Number(document.querySelector("#show-duration").value),intermission:Number(document.querySelector("#show-intermission").value),floor:document.querySelector("#show-floor").value,row:document.querySelector("#show-row").value,seat:document.querySelector("#show-seat").value}; document.querySelector("#viewing-count").textContent=t.times.replace("{n}",viewingCount(title||"untitled")); updatePoster(); }
function renderTickets() { document.querySelector("#ticket-fan").innerHTML=t.ticketLabels.map((label,index)=>`<button class="ghost-ticket ghost-ticket--${index}" type="button"><span>ENCORE</span><b>${label}</b><small>${t.ticketPreview}</small></button>`).join(""); }
showList.addEventListener("click",(event)=>{const option=event.target.closest(".show-option");if(!option)return;renderCustom(shows[Number(option.dataset.index)]);showScreen("custom");}); tabs.forEach((tab)=>tab.addEventListener("click",()=>showScreen(tab.dataset.screen))); applyCopy(); renderShows(); renderCustom(customShow); renderTickets();