const language = localStorage.getItem("encore-language") || "zh";
const copy = {
  zh: { exploreEyebrow:"今晚为你推荐", exploreTitle:"今晚，想看哪一场？", exploreIntro:"从一场演出开始，给时间一个值得期待的结尾。", customEyebrow:"你的专属场次", customTitle:"为自己安排一场演出。", customIntro:"从剧名到座位，为自己安排好这一晚。", presetIntro:"演出信息已带入，你也可以按需要调整。", walletEyebrow:"你收藏的 Encore", walletTitle:"我的票夹", walletIntro:"每张票根，都是一段已经好好度过的时间。", monthTotal:"本月观演", zeroMinutes:"0 分钟", collected:"已收藏", zeroTickets:"0 张票根", emptyNote:"第一场演出结束后，票根会在这里慢慢铺开。", navExplore:"探索剧目", navCustom:"自定义剧目", navWallet:"我的票夹", title:"剧目名称", titlePlaceholder:"填写剧目名称", venue:"观看地点", venuePlaceholder:"填写剧场或地点", duration:"专注时长", durationPlaceholder:"填写分钟数", durationHint:"建议填写 30–240 分钟之间的整数。", intermission:"中场休息", noIntermission:"无中场休息", seat:"座位号", viewing:"第几次观看", print:"打印入场券", floor:"层", row:"排", seatUnit:"座", times:"第 {n} 次", posterDefault:"一段属于你的安静时光", original:"ENCORE 原创场次", minutes:"分钟", interval:"中场 {n} 分钟", noInterval:"无中场", ticketLabels:["第一幕","中场","谢幕"], ticketPreview:"你的票根", saveShow:"将这场演出加入探索剧目" },
  en: { exploreEyebrow:"CURATED FOR TONIGHT", exploreTitle:"What will you see tonight?", exploreIntro:"Start with a performance. Give time an ending to look forward to.", customEyebrow:"YOUR PERSONAL MATINÉE", customTitle:"Plan a performance for yourself.", customIntro:"Set the title, the seat, and everything in between.", presetIntro:"Your performance details are ready to adjust.", walletEyebrow:"YOUR COLLECTED ENCORES", walletTitle:"My ticket wallet", walletIntro:"Every ticket marks time you spent well.", monthTotal:"This month", zeroMinutes:"0 min", collected:"Collected", zeroTickets:"0 tickets", emptyNote:"After your first performance, your tickets will slowly gather here.", navExplore:"Discover shows", navCustom:"Custom show", navWallet:"My tickets", title:"Show title", titlePlaceholder:"Enter a show title", venue:"Venue", venuePlaceholder:"Enter a theatre or place", duration:"Focus duration", durationPlaceholder:"Enter minutes", durationHint:"Please enter a whole number from 30 to 240 minutes.", intermission:"Intermission", noIntermission:"No intermission", seat:"Seat", viewing:"Viewing count", print:"Print admission ticket", floor:"F", row:"R", seatUnit:"S", times:"Viewing {n}", posterDefault:"A quiet time for you", original:"AN ENCORE ORIGINAL", minutes:"min", interval:"Interval {n} min", noInterval:"No interval", ticketLabels:["Act I","Interval","Curtain call"], ticketPreview:"YOUR TICKET", saveShow:"Add this show to Discover" }
};
const t=copy[language];
const shows=[
  {id:"witch",titleZh:"女巫",titleEn:"The Witch to Be",venueZh:"上海话剧艺术中心 D6 空间",venueEn:"D6 Space, Shanghai Dramatic Arts Centre",duration:130,intermission:10,floor:"1",row:"11",seat:"16"},
  {id:"phantom",titleZh:"歌剧魅影",titleEn:"The Phantom of the Opera",venueZh:"北京天桥艺术中心大剧场",venueEn:"Grand Theatre, Beijing Tianqiao Performing Arts Center",duration:155,intermission:20,floor:"1",row:"17",seat:"13"},
  {id:"human",titleZh:"人间失格",titleEn:"No Longer Human",venueZh:"北京保利剧院",venueEn:"Poly Theatre, Beijing",duration:210,intermission:20,floor:"1",row:"6",seat:"35"},
  {id:"interview",titleZh:"面试",titleEn:"Interview",venueZh:"北京世纪剧院",venueEn:"Century Theatre, Beijing",duration:110,intermission:0,floor:"1",row:"17",seat:"12"},
  {id:"hedwig",titleZh:"海德薇",titleEn:"Hedwig",venueZh:"上海北外滩友邦大剧院",venueEn:"AIA Grand Theatre, Shanghai",duration:100,intermission:0,floor:"1",row:"18",seat:"51"},
  {id:"sword",titleZh:"锦衣卫之刀与花",titleEn:"The Emperor's Shadow: Blades and Flowers",venueZh:"北京天桥艺术中心大剧场",venueEn:"Grand Theatre, Beijing Tianqiao Performing Arts Center",duration:180,intermission:15,floor:"1",row:"19",seat:"31"},
  {id:"six",titleZh:"六个说谎的大学生",titleEn:"Six Lying College Students",venueZh:"天津大剧院歌剧厅",venueEn:"Tianjin Grand Theatre Opera Hall",duration:135,intermission:15,floor:"3",row:"5",seat:"25"}
];
const customShow={id:"custom",titleZh:"",titleEn:"",venueZh:"",venueEn:"",duration:90,intermission:0,floor:"",row:"",seat:""}; let selectedShow={...customShow};
const titleOf=(show)=>language==="zh"?show.titleZh:show.titleEn; const venueOf=(show)=>language==="zh"?show.venueZh:show.venueEn; const allShows=()=>[...shows,...JSON.parse(localStorage.getItem("encore-saved-shows")||"[]")]; const formatInterval=(value)=>value?t.interval.replace("{n}",value):t.noInterval;
const showList=document.querySelector("#show-list"),screens=document.querySelectorAll(".screen"),tabs=document.querySelectorAll(".tab");
function viewingCount(title){const tickets=JSON.parse(localStorage.getItem("encore-tickets")||"[]");return tickets.filter((ticket)=>ticket.title?.trim()===title.trim()).length+1;}
function applyCopy(){document.documentElement.lang=language==="zh"?"zh-CN":"en";document.querySelectorAll("[data-i18n]").forEach((node)=>node.textContent=t[node.dataset.i18n]);document.querySelector(".continue-button").childNodes[0].nodeValue=`${t.print} `;document.querySelector("#save-show-row span:last-child").textContent=t.saveShow;}
function showScreen(name){screens.forEach((screen)=>screen.classList.toggle("screen--active",screen.id===`screen-${name}`));tabs.forEach((tab)=>tab.classList.toggle("tab--active",tab.dataset.screen===name));history.replaceState(null,"",`${location.pathname}${location.search}#${name}`);window.scrollTo({top:0,behavior:"smooth"});}
function durationOptions(selected){return Array.from({length:31},(_,i)=>90+i*5).map((value)=>`<option value="${value}" ${value===selected?"selected":""}>${value} ${t.minutes}</option>`).join("");}
function renderShows(){showList.innerHTML=allShows().map((show,index)=>`<button class="show-option" type="button" data-index="${index}"><span class="show-option__art poster-art--${show.id}" aria-hidden="true"><i></i><i></i><i></i></span><span class="show-option__copy"><small>${venueOf(show)}</small><b>${titleOf(show)}</b><em>${show.duration} ${t.minutes} · ${formatInterval(show.intermission)}</em></span><span class="show-option__arrow">›</span></button>`).join("");}
function updatePoster(){const title=titleOf(selectedShow).trim()||t.posterDefault;document.querySelector("#poster-card").className=`poster-card poster-card--${selectedShow.id}`;document.querySelector("#poster-kicker").textContent=venueOf(selectedShow).trim()||t.original;document.querySelector("#poster-title").textContent=title;document.querySelector("#poster-meta").textContent=`${selectedShow.duration} ${t.minutes.toUpperCase()} · ${formatInterval(selectedShow.intermission).toUpperCase()}`;}
function renderCustom(show){selectedShow={...show};const preset=show.id!=="custom";const durationControl=preset?`<select id="show-duration">${durationOptions(show.duration)}</select>`:`<input id="show-duration" type="number" inputmode="numeric" min="30" max="240" step="1" value="${show.duration}" placeholder="${t.durationPlaceholder}" aria-describedby="duration-hint" />`;document.querySelector("#custom-title").textContent=preset?(language==="zh"?`今晚观看《${titleOf(show)}》`:`Tonight: ${titleOf(show)}`):t.customTitle;document.querySelector("#custom-subtitle").textContent=preset?t.presetIntro:t.customIntro;document.querySelector("#save-show-row").hidden=preset;document.querySelector("#save-show").checked=false;document.querySelector("#settings-list").innerHTML=`<label class="form-row form-row--title"><span class="form-label">${t.title}</span><input id="show-title" value="${show.id==="custom"?"":titleOf(show)}" placeholder="${t.titlePlaceholder}" maxlength="42" /></label><label class="form-row"><span class="form-label">${t.venue}</span><input id="show-venue" value="${venueOf(show)}" placeholder="${t.venuePlaceholder}" maxlength="55" /></label><label class="form-row form-row--duration"><span class="form-label">${t.duration}</span>${durationControl}<small id="duration-hint" class="duration-hint" hidden>${t.durationHint}</small></label><label class="form-row"><span class="form-label">${t.intermission}</span><select id="show-intermission"><option value="0" ${show.intermission===0?"selected":""}>${t.noIntermission}</option><option value="10" ${show.intermission===10?"selected":""}>10 ${t.minutes}</option><option value="15" ${show.intermission===15?"selected":""}>15 ${t.minutes}</option><option value="20" ${show.intermission===20?"selected":""}>20 ${t.minutes}</option></select></label><div class="form-row form-row--seat"><span class="form-label">${t.seat}</span><span class="seat-inputs"><input id="show-floor" inputmode="numeric" value="${show.floor}" placeholder="${t.floor}" /><i>${t.floor}</i><input id="show-row" inputmode="numeric" value="${show.row}" placeholder="${t.row}" /><i>${t.row}</i><input id="show-seat" inputmode="numeric" value="${show.seat}" placeholder="${t.seatUnit}" /><i>${t.seatUnit}</i></span></div><div class="form-row"><span class="form-label">${t.viewing}</span><strong id="viewing-count">${t.times.replace("{n}",viewingCount(titleOf(show)||"untitled"))}</strong></div>`;document.querySelectorAll("#settings-list input,#settings-list select").forEach((input)=>input.addEventListener("input",syncForm));updatePoster();}
function hasValidDuration(){const value=Number(document.querySelector("#show-duration").value);return Number.isInteger(value)&&value>=30&&value<=240;}
function syncForm(){const title=document.querySelector("#show-title").value,venue=document.querySelector("#show-venue").value,duration=Number(document.querySelector("#show-duration").value),hint=document.querySelector("#duration-hint");hint.hidden=hasValidDuration();selectedShow={...selectedShow,titleZh:title,titleEn:title,venueZh:venue,venueEn:venue,duration,intermission:Number(document.querySelector("#show-intermission").value),floor:document.querySelector("#show-floor").value,row:document.querySelector("#show-row").value,seat:document.querySelector("#show-seat").value};document.querySelector("#viewing-count").textContent=t.times.replace("{n}",viewingCount(title||"untitled"));updatePoster();}
function ticketKey(ticket,index){return `v2-${ticket.id||`legacy-${ticket.completedAt||ticket.completedDate||"draft"}-${ticket.title||"ticket"}`}`}
function renderTickets(){const tickets=JSON.parse(localStorage.getItem("encore-tickets")||"[]"),recent=tickets.slice(-3);const monthMinutes=tickets.reduce((total,ticket)=>total+(ticket.status==="failed"?0:Number(ticket.actualMinutes??ticket.duration??0)),0);document.querySelector("#month-minutes").textContent=`${monthMinutes} ${t.minutes}`;document.querySelector("#ticket-total").textContent=language==="zh"?`${tickets.length} 张票根`:`${tickets.length} tickets`;document.querySelector(".empty-note").hidden=tickets.length>0;document.querySelector("#ticket-fan").innerHTML=(recent.length?recent:t.ticketLabels.map((label)=>({title:label}))).map((ticket,index)=>{const isRealTicket=Boolean(ticket.completedAt||ticket.completedDate),failed=ticket.status==="failed",key=ticketKey(ticket,index),drawing=localStorage.getItem(`encore-ticket-signature-${key}`),date=ticket.completedDate||(ticket.completedAt?new Date(ticket.completedAt).toLocaleDateString("zh-CN"):"");const record=!isRealTicket?"":failed?(language==="zh"?`${date} 未观演《${ticket.title}》`:`${date} · Not watched`):(language==="zh"?`${date} 完成《${ticket.title}》${ticket.actualMinutes} 分钟`:`${date} · ${ticket.actualMinutes} min completed`);return `<button class="ghost-ticket ghost-ticket--${index}${failed?" ghost-ticket--failed":""}${drawing?" ghost-ticket--signed":""}" type="button" data-ticket-key="${key}" data-ticket-title="${ticket.title||""}" ${!isRealTicket||failed?"disabled":""} ${drawing?`style="--signature:url('${drawing}')"`:""}><span>ENCORE</span><b>${ticket.title}</b><small>${ticket.venue||t.ticketPreview}</small>${record?`<i>${record}</i>`:""}</button>`;}).join("");}
showList.addEventListener("click",(event)=>{const option=event.target.closest(".show-option");if(!option)return;renderCustom(allShows()[Number(option.dataset.index)]);showScreen("custom");});tabs.forEach((tab)=>tab.addEventListener("click",()=>{if(tab.dataset.screen==="custom")renderCustom(customShow);showScreen(tab.dataset.screen);}));document.querySelector("#print-ticket").addEventListener("click",(event)=>{if(!titleOf(selectedShow).trim()){event.preventDefault();document.querySelector("#show-title").focus();return;}if(!hasValidDuration()){event.preventDefault();document.querySelector("#duration-hint").hidden=false;document.querySelector("#show-duration").focus();return;}if(selectedShow.id==="custom"&&document.querySelector("#save-show").checked){const saved=JSON.parse(localStorage.getItem("encore-saved-shows")||"[]");if(!saved.some((show)=>show.titleZh===selectedShow.titleZh))localStorage.setItem("encore-saved-shows",JSON.stringify([...saved,{...selectedShow,id:`saved-${Date.now()}`}]))}sessionStorage.setItem("encore-current-show",JSON.stringify(selectedShow));});applyCopy();renderShows();renderCustom(customShow);renderTickets();if(location.hash==="#wallet")showScreen("wallet");
const signatureDialog=document.querySelector("#signature-dialog"),signatureCanvas=document.querySelector("#signature-canvas"),signatureContext=signatureCanvas.getContext("2d"),inkCanvas=document.createElement("canvas"),inkContext=inkCanvas.getContext("2d"),signatureClose=document.querySelector("#signature-close"),signatureClear=document.querySelector("#signature-clear"),signatureUndo=document.querySelector("#signature-undo"),ticketDetail=document.querySelector("#ticket-detail"),ticketDetailClose=document.querySelector("#ticket-detail-close"),ticketDetailSign=document.querySelector("#ticket-detail-sign");let signatureKey="",drawing=false,lastPoint=null,markerColor="#b98a36",signatureHistory=[],activeTicketButton=null;
function signatureCopy(){const zh=language==="zh";document.querySelector("#signature-title").textContent=zh?"为我的票根签名":"Sign my ticket";document.querySelector("#signature-tool-label").textContent=zh?"选择马克笔":"Choose a marker";signatureUndo.textContent=zh?"撤回":"Undo";signatureClear.textContent=zh?"清除":"Clear";document.querySelector("#signature-note").textContent=zh?"你的笔迹会保存到这张票根。":"Your mark is saved with this ticket.";}
function drawTicketBase(){const rect=signatureCanvas.getBoundingClientRect(),title=activeTicketButton?.dataset.ticketTitle||"ENCORE",venue=activeTicketButton?.querySelector("small")?.textContent||"";signatureContext.fillStyle="#fffaf0";signatureContext.fillRect(0,0,rect.width,rect.height);signatureContext.fillStyle="#6c2635";signatureContext.font="700 10px -apple-system, BlinkMacSystemFont, sans-serif";signatureContext.fillText("ENCORE / TICKET STUB",20,25);signatureContext.fillStyle="#24211e";signatureContext.font="30px Didot, Songti SC, serif";signatureContext.fillText(title,20,66);signatureContext.fillStyle="#70675e";signatureContext.font="11px -apple-system, BlinkMacSystemFont, sans-serif";signatureContext.fillText(venue,20,87);signatureContext.strokeStyle="#c6b9a8";signatureContext.setLineDash([4,4]);signatureContext.beginPath();signatureContext.moveTo(20,105);signatureContext.lineTo(rect.width-20,105);signatureContext.stroke();signatureContext.setLineDash([]);signatureContext.fillStyle="#80776e";signatureContext.font="9px -apple-system, BlinkMacSystemFont, sans-serif";signatureContext.fillText("FOCUS TIME",20,127);signatureContext.fillText("ENCORE",rect.width-92,127);}
function resizeSignatureCanvas(){const rect=signatureCanvas.getBoundingClientRect(),ratio=Math.max(1,window.devicePixelRatio||1),savedDrawing=signatureKey&&localStorage.getItem(`encore-ticket-signature-${signatureKey}`);signatureCanvas.width=Math.round(rect.width*ratio);signatureCanvas.height=Math.round(rect.height*ratio);inkCanvas.width=signatureCanvas.width;inkCanvas.height=signatureCanvas.height;signatureContext.setTransform(ratio,0,0,ratio,0,0);inkContext.setTransform(ratio,0,0,ratio,0,0);signatureContext.lineCap=inkContext.lineCap="round";signatureContext.lineJoin=inkContext.lineJoin="round";drawTicketBase();signatureHistory=[savedDrawing||null];if(savedDrawing){const image=new Image();image.onload=()=>{signatureContext.drawImage(image,0,0,rect.width,rect.height);inkContext.drawImage(image,0,0,rect.width,rect.height)};image.src=savedDrawing;}}
function saveSignature(){if(!signatureKey)return;const snapshot=inkCanvas.toDataURL("image/png");if(signatureHistory.at(-1)!==snapshot)signatureHistory.push(snapshot);localStorage.setItem(`encore-ticket-signature-${signatureKey}`,snapshot);renderTickets();}
function restoreSignature(snapshot){signatureContext.clearRect(0,0,signatureCanvas.width,signatureCanvas.height);inkContext.clearRect(0,0,inkCanvas.width,inkCanvas.height);drawTicketBase();if(!snapshot)return;const image=new Image();image.onload=()=>{signatureContext.drawImage(image,0,0,signatureCanvas.getBoundingClientRect().width,signatureCanvas.getBoundingClientRect().height);inkContext.drawImage(image,0,0,signatureCanvas.getBoundingClientRect().width,signatureCanvas.getBoundingClientRect().height)};image.src=snapshot;}
function pointFor(event){const rect=signatureCanvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
signatureCanvas.addEventListener("pointerdown",(event)=>{drawing=true;lastPoint=pointFor(event);signatureCanvas.setPointerCapture(event.pointerId);});signatureCanvas.addEventListener("pointermove",(event)=>{if(!drawing)return;const point=pointFor(event);[signatureContext,inkContext].forEach((context)=>{context.strokeStyle=markerColor;context.lineWidth=3.2;context.beginPath();context.moveTo(lastPoint.x,lastPoint.y);context.lineTo(point.x,point.y);context.stroke();});lastPoint=point;});["pointerup","pointercancel"].forEach((name)=>signatureCanvas.addEventListener(name,()=>{if(drawing){drawing=false;lastPoint=null;saveSignature();}}));
function closeSignature(){signatureDialog.hidden=true;signatureDialog.setAttribute("aria-hidden","true");signatureKey="";}
function closeTicketDetail(){ticketDetail.hidden=true;ticketDetail.setAttribute("aria-hidden","true");}
function openSignature(){if(!activeTicketButton)return;signatureKey=activeTicketButton.dataset.ticketKey;document.querySelector("#signature-ticket-name").textContent=activeTicketButton.dataset.ticketTitle;signatureCopy();closeTicketDetail();signatureDialog.hidden=false;signatureDialog.setAttribute("aria-hidden","false");requestAnimationFrame(resizeSignatureCanvas);}
document.querySelector("#ticket-fan").addEventListener("click",(event)=>{const ticket=event.target.closest(".ghost-ticket:not(:disabled)");if(!ticket)return;activeTicketButton=ticket;signatureKey=ticket.dataset.ticketKey;document.querySelector("#ticket-detail-title").textContent=ticket.dataset.ticketTitle;document.querySelector("#ticket-detail-venue").textContent=ticket.querySelector("small")?.textContent||"";document.querySelector("#ticket-detail-time").textContent=ticket.querySelector("i")?.textContent||"—";document.querySelector("#ticket-detail-seat").textContent="ENCORE";document.querySelector("#ticket-detail-status").textContent=language==="zh"?"已完成":"Completed";const drawing=localStorage.getItem(`encore-ticket-signature-${signatureKey}`),signatureImage=document.querySelector("#ticket-detail-signature");signatureImage.hidden=!drawing;if(drawing)signatureImage.src=drawing;ticketDetail.hidden=false;ticketDetail.setAttribute("aria-hidden","false");});document.querySelectorAll(".marker").forEach((marker)=>marker.addEventListener("click",()=>{markerColor=marker.dataset.color;document.querySelectorAll(".marker").forEach((button)=>button.classList.toggle("is-selected",button===marker));}));signatureClear.addEventListener("click",()=>{signatureHistory=[null];localStorage.removeItem(`encore-ticket-signature-${signatureKey}`);inkContext.clearRect(0,0,inkCanvas.width,inkCanvas.height);drawTicketBase();renderTickets();});signatureUndo.addEventListener("click",()=>{if(signatureHistory.length<2)return;signatureHistory.pop();const previous=signatureHistory.at(-1);if(previous)localStorage.setItem(`encore-ticket-signature-${signatureKey}`,previous);else localStorage.removeItem(`encore-ticket-signature-${signatureKey}`);restoreSignature(previous);renderTickets();});signatureClose.addEventListener("click",closeSignature);signatureDialog.addEventListener("click",(event)=>{if(event.target===signatureDialog)closeSignature();});ticketDetailClose.addEventListener("click",closeTicketDetail);ticketDetail.addEventListener("click",(event)=>{if(event.target===ticketDetail)closeTicketDetail();});ticketDetailSign.addEventListener("click",openSignature);
document.querySelector("#language-toggle").addEventListener("click",()=>{const active=document.querySelector(".screen--active")?.id.replace("screen-","")||"custom";history.replaceState(null,"",`${location.pathname}${location.search}#${active}`);localStorage.setItem("encore-language",language==="zh"?"en":"zh");location.reload();});
document.querySelector("#ticket-detail-download").addEventListener("click",()=>{if(!activeTicketButton)return;const canvas=document.createElement("canvas"),context=canvas.getContext("2d"),title=activeTicketButton.dataset.ticketTitle||"Encore",venue=activeTicketButton.querySelector("small")?.textContent||"ENCORE",time=document.querySelector("#ticket-detail-time").textContent||"—";canvas.width=1200;canvas.height=730;context.fillStyle="#fffaf0";context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle="#6c2635";context.font="700 24px -apple-system, BlinkMacSystemFont, sans-serif";context.fillText("ENCORE / TICKET STUB",70,80);context.fillStyle="#24211e";context.font="76px Didot, Songti SC, serif";context.fillText(title,70,202);context.fillStyle="#70675e";context.font="28px -apple-system, BlinkMacSystemFont, sans-serif";context.fillText(venue,70,252);context.strokeStyle="#c6b9a8";context.setLineDash([12,12]);context.beginPath();context.moveTo(70,306);context.lineTo(1130,306);context.stroke();context.setLineDash([]);context.fillStyle="#80776e";context.font="22px -apple-system, BlinkMacSystemFont, sans-serif";context.fillText("FOCUS TIME",70,370);context.fillStyle="#24211e";context.font="600 34px -apple-system, BlinkMacSystemFont, sans-serif";context.fillText(time,70,418);const signature=localStorage.getItem(`encore-ticket-signature-${activeTicketButton.dataset.ticketKey}`),download=()=>{const link=document.createElement("a");link.download=`${title}-Encore-ticket.png`;link.href=canvas.toDataURL("image/png");link.click();};if(signature){const image=new Image();image.onload=()=>{context.drawImage(image,0,0,canvas.width,canvas.height);download()};image.src=signature}else download();});
function setFieldHint(row,id,className,message,show){let hint=row.querySelector(`#${id}`);if(!hint){hint=document.createElement("small");hint.id=id;hint.className=className;row.append(hint)}hint.textContent=message;hint.hidden=!show;}
function fitPosterTitle(){const node=document.querySelector("#poster-title"),length=Array.from(node.textContent.trim()).length;node.style.fontSize=length>30?"23px":length>18?"28px":"";}
new MutationObserver(fitPosterTitle).observe(document.querySelector("#poster-title"),{childList:true,characterData:true,subtree:true});fitPosterTitle();
document.addEventListener("input",event=>{const input=event.target;if(input.id==="show-title"){const raw=Array.from(input.value),tooLong=raw.length>40;if(tooLong){input.value=raw.slice(0,40).join("");syncForm()}const row=input.closest(".form-row--title"),length=Array.from(input.value.trim()).length;setFieldHint(row,"title-hint","title-hint",tooLong?(language==="zh"?"剧目名称最多支持 40 个字符。":"Show titles can be up to 40 characters."):(language==="zh"?"建议将剧目名称控制在 10 个字以内，以获得更完整的票根呈现效果。":"For the best ticket presentation, keep the title to 10 characters or fewer."),tooLong||length>10);fitPosterTitle();}if(input.id==="show-venue"){const raw=Array.from(input.value),tooLong=raw.length>54;if(tooLong){input.value=raw.slice(0,54).join("");syncForm()}const row=input.closest(".form-row");row.style.position="relative";setFieldHint(row,"venue-hint","venue-hint",language==="zh"?"观看地点最多支持 54 个字符。":"Venues can be up to 54 characters.",tooLong);}});
const requestedScreen=location.hash.slice(1);if(["explore","custom","wallet"].includes(requestedScreen))showScreen(requestedScreen);
const today = new Date();

document.getElementById("current-month").textContent =
`${today.getMonth() + 1}月`;

document.getElementById("current-day").textContent = String(today.getDate());
